apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: deployment-manager
rules:
- apiGroups: ["apps"]  # "apps" indicates the APP API group
  resources: ["*"]
  verbs: ["*"]

