apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-test-binding
  namespace: test
subjects:
- kind: ServiceAccount
  name: my-seracc
  apiGroup: ""
roleRef:
  kind: Role 
  name: rbac-test # role name
  apiGroup: ""
